#!/bin/Rscript

buys = read.csv("data/buy.csv");
sells = read.csv("data/sell.csv");

# returns a per-asset "cost-basis" vector for buy transactions.
add_basis_col <- function() {
  (buys$val.tx * buys$asset + buys$fee)/buys$asset # val-tx * asset + fee
}

# returns a "proceeds" column for sell transactions.
add_proceeds_col = function() {
  sells$asset * sells$val.tx - sells$fee # asset * val-tx - fee
}

# returns "fifo" vector for buy transasctions.
add_fifo = function() {
  buys$asset
}

create_entry = function (asset, tick, aquired, sold, pro, base, gain) {
  entry = data.frame (asset, tick, aquired, sold, pro, base, gain)
  write.table(entry, file = "data/data.csv", sep = ",", append = TRUE, quote = FALSE, col.names = FALSE, row.names = FALSE)
}

buys$"cost-basis" = add_basis_col()
sells$proceeds = add_proceeds_col()
sells$fifo = sells$asset

buys$fifo = add_fifo()
buys$index = 1:nrow(buys)
sells$index = 1:nrow(sells)

i = 1

while (sells[i,]$fifo > 0 & !(i > nrow(sells))) {
  t<- sells[i,]$ticker # get ticker

  # subset of buys with sell ticker
  stack = buys[buys$ticker == t & buys$fifo > 0,]
  # in fifo fashion, get the buy that was first put in the stack
  first = head(stack,1)

  index = first$index
  # sell asset amount is greater than buy on top of the stack
  if(sells[i,]$fifo > first$fifo) {

    asset = sells[i,]$fifo
    sells[i,]$fifo = sells[i,]$fifo - first$fifo
    asset = asset - sells[i,]$fifo
    buys[index,]$fifo = 0

    date_aquired = first$date
    date_sold = sells[i,]$date
    proceeds = sells[i,]$"val.tx" * asset
    total_basis = first$"cost-basis" * asset
    print(proceeds)
    print(total_basis)
    gain = proceeds - total_basis

    # create an entry
    create_entry(asset, t,date_aquired, date_sold, proceeds,
      total_basis, gain)

    next
  }
  # sell asset amount is less than buy on top of the stack
  if(sells[i,]$fifo < first$fifo) {
    asset = sells[i,]$fifo
    date_aquired = first$date
    date_sold = sells[i,]$date
    proceeds = sells[i,]$"val.tx" * asset
    total_basis = first$"cost-basis" * asset
    gain = proceeds - total_basis

    # create an entry
    create_entry(asset, t,date_aquired, date_sold, proceeds,
      total_basis, gain)

    buys[index,]$fifo = first$fifo - sells[i,]$fifo
    sells[i,]$fifo = 0
    i = i + 1
    next
  }
  # sell asset amount is equal to buy on top of the stack
  if(sells[i,]$fifo == first$fifo) {
    asset = sells[i,]$fifo
    date_aquired = first$date
    date_sold = sells[i,]$date
    proceeds = sells[i,]$"val.tx" * asset
    total_basis = first$"cost-basis" * asset
    gain = proceeds - total_basis

    # create an entry
    create_entry(asset, t,date_aquired, date_sold, proceeds,
      total_basis, gain)

    sells[i,]$fifo = 0
    if(!is.na(buys[i,]$fifo)) {
      buys[i,]$fifo = 0
    }
    i = i + 1
    next
  }
  print("error occured")
}
buys;sells

